"""Builds engine/data-hr-local-units.js from the Tax Administration's local income tax rate table.

Usage: python tools/build_hr_local_units.py <table.xlsx> <valid-from YYYY-MM>

The table is published yearly on porezna-uprava.gov.hr ("Tablica poreznih stopa godišnjeg
poreza na dohodak za <year> godinu"). Columns: Rbr., Šifra, Ime, Uplatni račun, Broj NN,
Niža stopa, Viša stopa, Stupanje na snagu.
"""
import json
import re
import sys
from pathlib import Path

import openpyxl

SMALL_WORDS = {"u", "na", "pri", "kod", "i", "nad", "pod", "od", "do", "kraj"}
OUT = Path(__file__).resolve().parent.parent / "engine" / "data-hr-local-units.js"


def title_case(name):
    words = re.split(r"(\s+|-)", name.strip().lower())
    out = []
    for idx, w in enumerate(words):
        if not w or w.isspace() or w == "-":
            out.append(w)
        elif idx > 0 and w in SMALL_WORDS:
            out.append(w)
        else:
            out.append(w[0].upper() + w[1:])
    return "".join(out)


def main(path, valid_from):
    ws = openpyxl.load_workbook(path, data_only=True).active
    units = []
    for row in ws.iter_rows(min_row=2, values_only=True):
        if row[1] is None:
            continue
        code, name, lower, higher = int(row[1]), str(row[2]), row[5], row[6]
        units.append([code, title_case(name), round(lower * 10000), round(higher * 10000)])
    codes = [u[0] for u in units]
    assert len(codes) == len(set(codes)), "duplicate codes"
    for code, name, lower, higher in units:
        assert 1500 <= lower <= 2300 and 2500 <= higher <= 3300, (code, name, lower, higher)
    units.sort(key=lambda u: u[1])
    body = ",\n".join("  " + json.dumps(u, ensure_ascii=False) for u in units)
    OUT.write_text(
        "// Generated by tools/build_hr_local_units.py - do not edit by hand.\n"
        "// Source: Porezna uprava, local income tax rate table.\n"
        "// Rows: [code, name, lower rate bp, higher rate bp]\n"
        f"export const HR_LOCAL_UNITS_VALID_FROM = '{valid_from}';\n"
        f"export const HR_LOCAL_UNITS = [\n{body},\n];\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"{len(units)} local units written to {OUT}")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
